#██████╗░███████╗██████╗░██████╗░░█████╗░  ██╗░░░░░██╗██████╗░
#██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗  ██║░░░░░██║██╔══██╗
#██████╦╝█████╗░░██████╦╝██████╔╝███████║  ██║░░░░░██║██████╦╝
#██╔══██╗██╔══╝░░██╔══██╗██╔══██╗██╔══██║  ██║░░░░░██║██╔══██╗
#██████╦╝███████╗██████╦╝██║░░██║██║░░██║  ███████╗██║██████╦╝
#╚═════╝░╚══════╝╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝  ╚══════╝╚═╝╚═════╝░
menu:
  slots: 18
  title: "hui"
  items:
    item1:
      type: dirt
      name: "test"
      slot: 1
      actions:
        a1:
          click: any # неуказан клик -> "any click"
          cmds:
            - "say test"